---
- name: Deploy new application version
  hosts: server_deploy
  connection: local
  become: true

  vars:
    image_version: "{{ build_number | default(lookup('env','BUILD_NUMBER')) | default('latest', true) }}"
    registry: "localhost:5000"

  tasks:

    - name: Pull new image version from local registry
      ansible.builtin.shell: >
        docker pull {{ registry }}/myapp:{{ image_version }}

    - name: Stop old container if exists
      ansible.builtin.shell: |
        docker stop myapp 2>/dev/null || true
        docker rm myapp 2>/dev/null || true

    - name: Start new container from pulled image
      ansible.builtin.shell: >
        docker run -d --name myapp -p 8080:80
        {{ registry }}/myapp:{{ image_version }}
